services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: mktplace-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/buysell
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123091991
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:16.0'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123091991